# Generated by Django 5.0.2 on 2024-02-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'endereco',
                'verbose_name_plural': 'enderecos',
            },
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da loja')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('date_of_fundation', models.DateField(verbose_name='Data da fundação')),
                ('image', models.ImageField(upload_to='media/products/%Y/%m/%d')),
            ],
        ),
    ]
