# Generated by Django 5.0.2 on 2024-02-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'loja', 'verbose_name_plural': 'lojas'},
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.address', verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/%Y/%m/%d'),
        ),
    ]
